# Generated by Django 5.2 on 2025-04-28 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClimateCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('rainfall', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CropRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=100)),
                ('optimal_temperature_min', models.FloatField()),
                ('optimal_temperature_max', models.FloatField()),
                ('optimal_humidity_min', models.FloatField()),
                ('optimal_humidity_max', models.FloatField()),
                ('optimal_rainfall_min', models.FloatField()),
                ('optimal_rainfall_max', models.FloatField()),
                ('soil_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SoilType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soil_ph', models.FloatField()),
                ('soil_texture', models.CharField(max_length=100)),
                ('soil_moisture', models.FloatField()),
            ],
        ),
    ]



