# Generated by Django 5.2 on 2025-06-19 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_place', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplaceitem',
            name='category',
            field=models.CharField(default='OTHER', max_length=20),
        ),
    ]
