# Generated by Django 5.2.3 on 2025-06-29 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_place', '0002_alter_marketplaceitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplaceitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
