# Generated by Django 5.2 on 2025-06-28 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_place', '0002_alter_marketplaceitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplaceitem',
            name='idealTemperature',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='marketplaceitem',
            name='suitability',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='marketplaceitem',
            name='imageUrl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='marketplaceitem',
            name='seller',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='marketplaceitem',
            name='date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]