# Generated by Django 5.2 on 2025-06-28 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_place', '0003_add_product_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplaceitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='marketplace_images/'),
        ),
    ]