# Generated by Django 5.2 on 2025-06-29 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_place', '0004_add_image_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplaceitem',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]