# Generated by Django 5.2 on 2025-07-02 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_place', '0007_merge_20250701_merged'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplaceitem',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_items', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='marketplaceitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='marketplace_images/'),
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
