import rice from "../assets/images/rice.png";
import soybeans from "../assets/images/soybeans.png";
import beans from "../assets/images/beans.png";
import wheat from "../assets/images/wheat.png";
import maize from "../assets/images/maize.png";
import nuts from "../assets/images/nuts.png";
import pigeonpeas from "../assets/images/pigeonpeas.png";
import cassava from "../assets/images/cassava.png";
import sorghum from "../assets/images/sorghum.jpg";
import greengrams from "../assets/images/greengrams.png";
import sunflower from "../assets/images/sunflower.jpg";
import sweetpotatoes from "../assets/images/sweetpotatoes.png";
import coffee from "../assets/images/coffee.png";
import tea from "../assets/images/tea.png";
import cashew from "../assets/images/cashew.png";
import sesame from "../assets/images/sesame.png";
import barley from "../assets/images/barley.png";
import cotton from "../assets/images/cotton.png";
import millet from "../assets/images/millet.png";
import cowpeas from "../assets/images/cowpeas.png";
import chickpeas from "../assets/images/chickpeas.png";
import bananas from "../assets/images/bananas.png";
import pineapple from "../assets/images/pineapple.png";
import passionfruit from "../assets/images/passionfruit.png";
import oranges from "../assets/images/oranges.png";
import lemons from "../assets/images/lemons.png";
import papaya from "../assets/images/papaya.png";
import mangoes from "../assets/images/mangoes.png";
import cabbage from "../assets/images/cabbage.png";
import avocados from "../assets/images/avocados.png";
import tomatoes from "../assets/images/tomatoes.png";
import onions from "../assets/images/onions.png";
import potatoes from "../assets/images/potatoes.png";
import carrots from "../assets/images/carrots.png";




export type crop = {
  name: string;
  image: string;
  price: string;
  seller: string;
  date: string;
  contact: string;
  wholesale: boolean;
  category: string;
  region: string;
  status: string;
};

// Sample crop data
export const crops: crop[] = [
 {
  name: 'Maize',
  image: maize,
  price: 'TZS 1800/kg',
  seller: 'Mkulima Asha',
  date: '2025-07-17',
  contact: '+255123456789',
  wholesale: true,
  category: 'cereals',
  region: 'Dodoma',
  status: 'Sold',
 },

 {
  name: 'Maize',
  image: maize,
  price: 'TZS 2200/kg',
  seller: 'Mkulima Asha',
  date: '2025-09-22',
  contact: '+255123456789',
  wholesale: true,
  category: 'cereals',
  region: 'Geita',
  status: 'Sold',
 },

 {
  name: 'Maize',
  image: maize,
  price: 'TZS 2000/kg',
  seller: 'Reagan',
  date: '2025-08-22',
  contact: '+255123456789',
  wholesale: true,
  category: 'cereals',
  region: 'Geita',
  status: 'Sold',
 },

{
    name: "Beans",
    price: "TZS 2000/kg",
    image: beans,
    seller: "Neema John",
    date: "2025-08-23",
    wholesale: false,
    contact: "0789123456",
    category: 'cereals',
    region: 'Mwanza',
    status: 'Available',
 },

 {
    name: "Beans",
    price: "TZS 1700/kg",
    image: beans,
    seller: "Neema John",
    date: "2025-10-19",
    wholesale: false,
    contact: "0789123456",
    category: 'cereals',
    region: 'Mwanza',
    status: 'Available',
 },
  {
    name: "Rice",
    price: "TZS 2000/kg",
    image: rice,
    seller: "James zaki",
    date: "2025-02-13",
    wholesale: true,
    contact: "0712345678",
    category: 'cereals',
    region: 'Kahama',
    status: 'Available',
  },

   {
    name: "Rice",
    price: "TZS 2500/kg",
    image: rice,
    seller: "James zaki",
    date: "2025-04-07",
    wholesale: true,
    contact: "0712345678",
    category: 'cereals',
    region: 'Kahama',
    status: 'Available',
  },

  {
    name: "Rice",
    price: "TZS 2700/kg",
    image: rice,
    seller: "James zaki",
    date: "2025-07-20",
    wholesale: true,
    contact: "0712345678",
    category: 'cereals',
    region: 'Kahama',
    status: 'Available',
  },

   {
    name: "Soy Beans",
    price: "TZS 2800/kg",
    image: soybeans,
    seller: "Asha",
    date: "2025-05-12",
    wholesale: false,
    contact: "0789123456",
    category: 'cereals',
    region: 'Dodoma',
    status: 'Available',
  },

  {
    name: "Soy Beans",
    price: "TZS 3000/kg",
    image: soybeans,
    seller: "Asha",
    date: "2025-08-11",
    wholesale: false,
    contact: "0789123456",
    category: 'cereals',
    region: 'Dodoma',
    status: 'Available',
  },

  {
    name: "Soy Beans",
    price: "TZS 2800/kg",
    image: soybeans,
    seller: "Asha",
    date: "2025-11-19",
    wholesale: false,
    contact: "0789123456",
    category: 'cereals',
    region: 'Dodoma',
    status: 'Available',
  },

  {
    name: "Wheat",
    price: "TZS 1000/kg",
    image: wheat,
    seller: "John",
    date: "2025-01-20",
    wholesale: true,
    contact: "0712345678",
    category: 'cereals',
    region: 'Mbeya',
    status: 'Available',
  },

  {
    name: "Wheat",
    price: "TZS 900/kg",
    image: wheat,
    seller: "John",
    date: "2025-05-07",
    wholesale: true,
    contact: "0712345678",
    category: 'cereals',
    region: 'Mbeya',
    status: 'Available',
  },

   {
    name: "Wheat",
    price: "TZS 1200/kg",
    image: wheat,
    seller: "John",
    date: "2025-07-10",
    wholesale: true,
    contact: "0712345678",
    category: 'cereals',
    region: 'Mbeya',
    status: 'Available',
  },
  
  {
    name: "Millet",
    price: "TZS 900/kg",
    image: millet,
    seller: "John",
    date: "2025-02-08",
    wholesale: true,
    contact: "0712345678",
    category: 'cereals',
    region: 'Shinyanga',
    status: 'Available',
  },

  {
    name: "Millet",
    price: "TZS 1100/kg",
    image: millet,
    seller: "John",
    date: "2025-05-212",
    wholesale: true,
    contact: "0712345678",
    category: 'cereals',
    region: 'Shinyanga',
    status: 'Available',
  },

    {
    name: "Millet",
    price: "TZS 1400/kg",
    image: millet,
    seller: "John",
    date: "2025-06-25",
    wholesale: true,
    contact: "0712345678",
    category: 'cereals',
    region: 'Shinyanga',
    status: 'Available',
  },
    {
    name: "Millet",
    price: "TZS 1600/kg",
    image: millet,
    seller: "John",
    date: "2025-09-20",
    wholesale: true,
    contact: "0712345678",
    category: 'cereals',
    region: 'Shinyanga',
    status: 'Available',
  },

 {
    name: "Beans",
    price: "TZS 1800/kg",
    image: soybeans,
    seller: "Asha",
    date: "2025-05-19",
    wholesale: false,
    contact: "0789123456",
    category: 'cereals',
    region: 'Arusha',
    status: 'Available',
  },
  
  {
    name: "Ground Nuts",
    price: "TZS 2200/kg",
    image: nuts,
    seller: "John",
    date: "2025-03-20",
    wholesale: true,
    contact: "0712345678",
    category: 'Nuts',
    region: 'Dodoma',
    status: 'Available',
  },

   {
    name: "Ground Nuts",
    price: "TZS 3000/kg",
    image: nuts,
    seller: "John",
    date: "2025-07-20",
    wholesale: true,
    contact: "0712345678",
    category: 'Nuts',
    region: 'Dodoma',
    status: 'Available',
  },

   {
    name: "Ground Nuts",
    price: "TZS 3500/kg",
    image: nuts,
    seller: "John",
    date: "2025-11-20",
    wholesale: true,
    contact: "0712345678",
    category: 'Nuts',
    region: 'Dodoma',
    status: 'Available',
  },

   {
  name: 'Maize',
  image: maize,
  price: 'TZS 1100/kg',
  seller: 'Mkulima Asha',
  date: '2025-03-22',
  contact: '+255123456789',
  wholesale: true,
  category: 'cereals',
  region: 'Kahama',
  status: 'Available',
 },
   {
  name: 'Maize',
  image: maize,
  price: 'TZS 2400/kg',
  seller: 'Mkulima Asha',
  date: '2025-09-20',
  contact: '+255123456789',
  wholesale: true,
  category: 'cereals',
  region: 'Tanga',
  status: 'Available',
 },

  {
    name: "Sunflower",
    price: "TZS 1800/kg",
    image: sunflower,
    seller: "Juma Bakari",
    date: "2025-01-16",
    wholesale: true,
    contact: "0755443322",
    category: "oilseeds",
    region: "Dodoma",
    status: "Available",
  },

  {
    name: "Sunflower",
    price: "TZS 1700/kg",
    image: sunflower,
    seller: "Juma Bakari",
    date: "2025-04-01",
    wholesale: true,
    contact: "0755443322",
    category: "oilseeds",
    region: "Dodoma",
    status: "Available",
  },

  {
    name: "Sunflower",
    price: "TZS 2000/kg",
    image: sunflower,
    seller: "Juma Bakari",
    date: "2025-07-18",
    wholesale: true,
    contact: "0755443322",
    category: "oilseeds",
    region: "Dodoma",
    status: "Available",
  },

  {
    name: "Sorghum",
    price: "TZS 1200/kg",
    image: sorghum,
    seller: "Asha Mwamba",
    date: "2025-06-20",
    wholesale: false,
    contact: "0788665544",
    category: "cereals",
    region: "Shinyanga",
    status: "Available",
  },

 {
    name: "Sorghum",
    price: "TZS 1100/kg",
    image: sorghum,
    seller: "Asha Mwamba",
    date: "2025-09-02",
    wholesale: false,
    contact: "0788665544",
    category: "cereals",
    region: "Shinyanga",
    status: "Sold",
  },

   {
    name: "Sorghum",
    price: "TZS 1500/kg",
    image: sorghum,
    seller: "Asha Mwamba",
    date: "2025-10-22",
    wholesale: false,
    contact: "0788665544",
    category: "cereals",
    region: "Shinyanga",
    status: "Sold",
  },

  {
    name: "Green Grams",
    price: "TZS 2500/kg",
    image: greengrams,
    seller: "Paul Mwakasege",
    date: "2025-02-05",
    wholesale: true,
    contact: "0733554466",
    category: "legumes",
    region: "Manyara",
    status: "Available",
  },

{
    name: "Green Grams",
    price: "TZS 2100/kg",
    image: greengrams,
    seller: "Paul Mwakasege",
    date: "2025-09-11",
    wholesale: true,
    contact: "0733554466",
    category: "legumes",
    region: "Manyara",
    status: "Available",
  },

  {
    name: "Pigeon Peas",
    price: "TZS 2300/kg",
    image: pigeonpeas,
    seller: "Neema Charles",
    date: "2025-08-15",
    wholesale: false,
    contact: "0766889900",
    category: "legumes",
    region: "Tanga",
    status: "Available",
  },
{
    name: "Pigeon Peas",
    price: "TZS 2600/kg",
    image: pigeonpeas,
    seller: "Neema Charles",
    date: "2025-10-30",
    wholesale: false,
    contact: "0766889900",
    category: "legumes",
    region: "Tanga",
    status: "Available",
  },

  {
    name: "Pigeon Peas",
    price: "TZS 1800/kg",
    image: pigeonpeas,
    seller: "Neema Charles",
    date: "2025-12-01",
    wholesale: false,
    contact: "0766889900",
    category: "legumes",
    region: "Tanga",
    status: "Available",
  },

  {
    name: "Cassava",
    price: "TZS 800/kg",
    image: cassava,
    seller: "Rajabu Simba",
    date: "2025-10-12",
    wholesale: true,
    contact: "0744778899",
    category: "tubers",
    region: "Mara",
    status: "Available",
  },

{
    name: "Cassava",
    price: "TZS 900/kg",
    image: cassava,
    seller: "Rajabu Simba",
    date: "2025-02-12",
    wholesale: true,
    contact: "0744778899",
    category: "tubers",
    region: "Mara",
    status: "Sold",
  },


  {
    name: "Cassava",
    price: "TZS 1200/kg",
    image: cassava,
    seller: "Rajabu Simba",
    date: "2025-05-20",
    wholesale: true,
    contact: "0744778899",
    category: "tubers",
    region: "Mara",
    status: "Sold",
  },

  {
    name: "Sweet Potatoes",
    price: "TZS 950/kg",
    image: sweetpotatoes,
    seller: "Grace Michael",
    date: "2025-11-08",
    wholesale: false,
    contact: "0755112233",
    category: "tubers",
    region: "Kagera",
    status: "Available",
  },
  {
    name: "Coffee",
    price: "TZS 3500/kg",
    image: coffee,
    seller: "Alfred Kato",
    date: "2025-07-14",
    wholesale: true,
    contact: "0788991122",
    category: "cash crops",
    region: "Kilimanjaro",
    status: "Available",
  },

  {
    name: "Coffee",
    price: "TZS 3500/kg",
    image: coffee,
    seller: "Alfred Kato",
    date: "2025-04-10",
    wholesale: true,
    contact: "0788991122",
    category: "cash crops",
    region: "Kilimanjaro",
    status: "Available",
  },

  {
    name: "Coffee",
    price: "TZS 3800/kg",
    image: coffee,
    seller: "Alfred Kato",
    date: "2025-07-14",
    wholesale: true,
    contact: "0788991122",
    category: "cash crops",
    region: "Kilimanjaro",
    status: "Available",
  },

{
    name: "Coffee",
    price: "TZS 3800/kg",
    image: coffee,
    seller: "Alfred Kato",
    date: "2025-09-15",
    wholesale: true,
    contact: "0788991122",
    category: "cash crops",
    region: "Kilimanjaro",
    status: "Available",
  },

  {
    name: "Tea",
    price: "TZS 2800/kg",
    image: tea,
    seller: "Ester Minja",
    date: "2025-03-20",
    wholesale: false,
    contact: "0711334455",
    category: "cash crops",
    region: "Njombe",
    status: "Sold",
  },

{
    name: "Tea",
    price: "TZS 2900/kg",
    image: tea,
    seller: "Ester Minja",
    date: "2025-05-29",
    wholesale: false,
    contact: "0711334455",
    category: "cash crops",
    region: "Njombe",
    status: "Available",
  },

  {
    name: "Tea",
    price: "TZS 3200/kg",
    image: tea,
    seller: "Ester Minja",
    date: "2025-05-30",
    wholesale: false,
    contact: "0711334455",
    category: "cash crops",
    region: "Njombe",
    status: "Sold",
  },

  {
    name: "Cashew Nuts",
    price: "TZS 4200/kg",
    image: cashew,
    seller: "Salim Juma",
    date: "2025-08-20",
    wholesale: true,
    contact: "0766554433",
    category: "Nuts",
    region: "Mtwara",
    status: "Available",
  },
  {
    name: "Sesame",
    price: "TZS 1900/kg",
    image: sesame,
    seller: "Zainabu Ally",
    date: "2025-01-15",
    wholesale: false,
    contact: "0744667788",
    category: "oilseeds",
    region: "Lindi",
    status: "Available",
  },

   {
    name: "Sesame",
    price: "TZS 2300/kg",
    image: sesame,
    seller: "Zainabu Ally",
    date: "2025-04-10",
    wholesale: false,
    contact: "0744667788",
    category: "oilseeds",
    region: "Lindi",
    status: "Available",
  },

   {
    name: "Sesame",
    price: "TZS 2500/kg",
    image: sesame,
    seller: "Zainabu Ally",
    date: "2025-09-01",
    wholesale: false,
    contact: "0744667788",
    category: "oilseeds",
    region: "Lindi",
    status: "Available",
  },

  {
    name: "Cotton",
    price: "TZS 1500/kg",
    image: cotton,
    seller: "John Petro",
    date: "2025-03-30",
    wholesale: true,
    contact: "0755778899",
    category: "cash crops",
    region: "Shinyanga",
    status: "Available",
  },

{
    name: "Cotton",
    price: "TZS 1800/kg",
    image: cotton,
    seller: "John Petro",
    date: "2025-07-01",
    wholesale: true,
    contact: "0755778899",
    category: "cash crops",
    region: "Shinyanga",
    status: "Sold",
  },

  {
    name: "Barley",
    price: "TZS 1400/kg",
    image: barley,
    seller: "Anna Mboya",
    date: "2025-06-10",
    wholesale: false,
    contact: "0788001122",
    category: "cereals",
    region: "Arusha",
    status: "Available",
  },

  {
    name: "Barley",
    price: "TZS 1750/kg",
    image: barley,
    seller: "Anna Mboya",
    date: "2025-08-05",
    wholesale: false,
    contact: "0788001122",
    category: "cereals",
    region: "Arusha",
    status: "Available",
  },

  {
    name: "Barley",
    price: "TZS 1800/kg",
    image: barley,
    seller: "Anna Mboya",
    date: "2025-09-21",
    wholesale: false,
    contact: "0788001122",
    category: "cereals",
    region: "Arusha",
    status: "Available",
  },

  {
    name: "Finger Millet",
    price: "TZS 1600/kg",
    image: millet,
    seller: "Elias Mwanga",
    date: "2025-10-10",
    wholesale: true,
    contact: "0733112233",
    category: "cereals",
    region: "Mbeya",
    status: "Available",
  },
  {
    name: "Cowpeas",
    price: "TZS 2100/kg",
    image: cowpeas,
    seller: "Sarah Juma",
    date: "2025-06-12",
    wholesale: false,
    contact: "0766223344",
    category: "legumes",
    region: "Rukwa",
    status: "Sold",
  },

  {
    name: "Cowpeas",
    price: "TZS 2300/kg",
    image: cowpeas,
    seller: "Sarah Juma",
    date: "2025-08-22",
    wholesale: false,
    contact: "0766223344",
    category: "legumes",
    region: "Rukwa",
    status: "Available",
  },

  {
    name: "Cowpeas",
    price: "TZS 2200/kg",
    image: cowpeas,
    seller: "Sarah Juma",
    date: "2025-10-21",
    wholesale: false,
    contact: "0766223344",
    category: "legumes",
    region: "Rukwa",
    status: "Sold",
  },

  {
    name: "Chickpeas",
    price: "TZS 2400/kg",
    image: chickpeas,
    seller: "David Mrosso",
    date: "2025-08-18",
    wholesale: true,
    contact: "0755887766",
    category: "legumes",
    region: "Simiyu",
    status: "Available",
  },

{
    name: "Chickpeas",
    price: "TZS 2500/kg",
    image: chickpeas,
    seller: "David Mrosso",
    date: "2025-09-19",
    wholesale: true,
    contact: "0755887766",
    category: "legumes",
    region: "Simiyu",
    status: "Available",
  },

  {
    name: "Tomatoes",
    price: "TZS 1200/kg",
    image: tomatoes,
    seller: "Maria Kileo",
    date: "2025-02-12",
    wholesale: false,
    contact: "0711445566",
    category: "vegetables",
    region: "Morogoro",
    status: "Available",
  },

{
    name: "Tomatoes",
    price: "TZS 1500/kg",
    image: tomatoes,
    seller: "Maria Kileo",
    date: "2025-03-12",
    wholesale: false,
    contact: "0711445566",
    category: "vegetables",
    region: "Morogoro",
    status: "Available",
  },

  {
    name: "Tomatoes",
    price: "TZS 2000/kg",
    image: tomatoes,
    seller: "Maria Kileo",
    date: "2025-04-09",
    wholesale: false,
    contact: "0711445566",
    category: "vegetables",
    region: "Morogoro",
    status: "Available",
  },

  {
    name: "Tomatoes",
    price: "TZS 2500/kg",
    image: tomatoes,
    seller: "Maria Kileo",
    date: "2025-07-16",
    wholesale: false,
    contact: "0711445566",
    category: "vegetables",
    region: "Morogoro",
    status: "Available",
  },

  {
    name: "Onions",
    price: "TZS 1100/kg",
    image: onions,
    seller: "Yusuph Mfinanga",
    date: "2025-06-25",
    wholesale: true,
    contact: "0788112233",
    category: "vegetables",
    region: "Dodoma",
    status: "Available",
  },

{
    name: "Onions",
    price: "TZS 2000/kg",
    image: onions,
    seller: "Yusuph Mfinanga",
    date: "2025-07-20",
    wholesale: true,
    contact: "0788112233",
    category: "vegetables",
    region: "Dodoma",
    status: "Sold",
  },

  {
    name: "Irish Potatoes",
    price: "TZS 1300/kg",
    image: potatoes,
    seller: "Robert Chalamila",
    date: "2025-08-08",
    wholesale: false,
    contact: "0755998877",
    category: "tubers",
    region: "Iringa",
    status: "Available",
  },
  {
    name: "Cabbage",
    price: "TZS 900/kg",
    image: cabbage,
    seller: "Esterina Mbowe",
    date: "2025-07-05",
    wholesale: true,
    contact: "0744556677",
    category: "vegetables",
    region: "Tanga",
    status: "Available",
  },
  {
    name: "Carrots",
    price: "TZS 950/kg",
    image: carrots,
    seller: "Jamal Kombo",
    date: "2025-04-10",
    wholesale: false,
    contact: "0766778899",
    category: "vegetables",
    region: "Arusha",
    status: "Available",
  },

 {
    name: "Carrots",
    price: "TZS 1000/kg",
    image: carrots,
    seller: "Jamal Kombo",
    date: "2025-06-10",
    wholesale: false,
    contact: "0766778899",
    category: "vegetables",
    region: "Arusha",
    status: "Sold",
  },

   {
    name: "Carrots",
    price: "TZS 1100/kg",
    image: carrots,
    seller: "Jamal Kombo",
    date: "2025-09-12",
    wholesale: false,
    contact: "0766778899",
    category: "vegetables",
    region: "Arusha",
    status: "Available",
  },

  {
    name: "Bananas",
    price: "TZS 800/kg",
    image: bananas,
    seller: "Pendo Shoo",
    date: "2025-08-22",
    wholesale: true,
    contact: "0755113344",
    category: "fruits",
    region: "Kagera",
    status: "Available",
  },


  {
    name: "Bananas",
    price: "TZS 750/kg",
    image: bananas,
    seller: "Pendo Shoo",
    date: "2025-09-22",
    wholesale: true,
    contact: "0755113344",
    category: "fruits",
    region: "Kagera",
    status: "Available",
  },

  {
    name: "Bananas",
    price: "TZS 600/kg",
    image: bananas,
    seller: "Pendo Shoo",
    date: "2025-10-10",
    wholesale: true,
    contact: "0755113344",
    category: "fruits",
    region: "Kagera",
    status: "Available",
  },

  {
    name: "Avocados",
    price: "TZS 1500/kg",
    image: avocados,
    seller: "Michael Mwenda",
    date: "2025-04-30",
    wholesale: false,
    contact: "0788223344",
    category: "fruits",
    region: "Kilimanjaro",
    status: "Available",
  },

   {
    name: "Avocados",
    price: "TZS 1200/kg",
    image: avocados,
    seller: "Michael Mwenda",
    date: "2025-07-20",
    wholesale: false,
    contact: "0788223344",
    category: "fruits",
    region: "Kilimanjaro",
    status: "Available",
  },

   {
    name: "Avocados",
    price: "TZS 1800/kg",
    image: avocados,
    seller: "Michael Mwenda",
    date: "2025-09-21",
    wholesale: false,
    contact: "0788223344",
    category: "fruits",
    region: "Kilimanjaro",
    status: "Available",
  },

  {
    name: "Mangoes",
    price: "TZS 700/kg",
    image: mangoes,
    seller: "Asha Rashid",
    date: "2025-06-15",
    wholesale: true,
    contact: "0744115566",
    category: "fruits",
    region: "Coast",
    status: "Sold",
  },

{
    name: "Mangoes",
    price: "TZS 1000/kg",
    image: mangoes,
    seller: "Asha Rashid",
    date: "2025-09-12",
    wholesale: true,
    contact: "0744115566",
    category: "fruits",
    region: "Coast",
    status: "Available",
  },

  {
    name: "Pineapples",
    price: "TZS 1200/kg",
    image: pineapple,
    seller: "Juma Athumani",
    date: "2025-04-05",
    wholesale: false,
    contact: "0766557788",
    category: "fruits",
    region: "Morogoro",
    status: "Available",
  },

  {
    name: "Pineapples",
    price: "TZS 1600/kg",
    image: pineapple,
    seller: "Juma Athumani",
    date: "2025-06-01",
    wholesale: false,
    contact: "0766557788",
    category: "fruits",
    region: "Morogoro",
    status: "Available",
  },

  {
    name: "Pineapples",
    price: "TZS 1800/kg",
    image: pineapple,
    seller: "Juma Athumani",
    date: "2025-09-10",
    wholesale: false,
    contact: "0766557788",
    category: "fruits",
    region: "Morogoro",
    status: "Available",
  },

  {
    name: "Papaya",
    price: "TZS 850/kg",
    image: papaya,
    seller: "Zuhura Ally",
    date: "2025-08-10",
    wholesale: true,
    contact: "0755446677",
    category: "fruits",
    region: "Tanga",
    status: "Available",
  },
  {
    name: "Lemons",
    price: "TZS 950/kg",
    image: lemons,
    seller: "John Mrosso",
    date: "2025-07-20",
    wholesale: false,
    contact: "0711667788",
    category: "fruits",
    region: "Dodoma",
    status: "Available",
  },

{
    name: "Lemons",
    price: "TZS 1000/kg",
    image: lemons,
    seller: "John Mrosso",
    date: "2025-09-21",
    wholesale: false,
    contact: "0711667788",
    category: "fruits",
    region: "Dodoma",
    status: "Sold",
  },

  {
    name: "Lemons",
    price: "TZS 900/kg",
    image: lemons,
    seller: "John Mrosso",
    date: "2025-10-22",
    wholesale: false,
    contact: "0711667788",
    category: "fruits",
    region: "Dodoma",
    status: "Available",
  },

  {
    name: "Oranges",
    price: "TZS 800/kg",
    image: oranges,
    seller: "Grace Mwambene",
    date: "2025-06-28",
    wholesale: true,
    contact: "0788334455",
    category: "fruits",
    region: "Morogoro",
    status: "Available",
  },

{
    name: "Oranges",
    price: "TZS 1000/kg",
    image: oranges,
    seller: "Grace Mwambene",
    date: "2025-09-28",
    wholesale: true,
    contact: "0788334455",
    category: "fruits",
    region: "Morogoro",
    status: "Available",
  },

  {
    name: "Oranges",
    price: "TZS 1200/kg",
    image: oranges,
    seller: "Grace Mwambene",
    date: "2025-11-03",
    wholesale: true,
    contact: "0788334455",
    category: "fruits",
    region: "Morogoro",
    status: "Available",
  },

  {
    name: "Passion Fruits",
    price: "TZS 1800/kg",
    image: passionfruit,
    seller: "Daniel Mbegu",
    date: "2025-05-25",
    wholesale: false,
    contact: "0766998877",
    category: "fruits",
    region: "Iringa",
    status: "Available",
  },

  {
    name: "Passion Fruits",
    price: "TZS 1900/kg",
    image: passionfruit,
    seller: "Daniel Mbegu",
    date: "2025-08-04",
    wholesale: false,
    contact: "0766998877",
    category: "fruits",
    region: "Iringa",
    status: "Available",
  },

  {
    name: "Passion Fruits",
    price: "TZS 2100/kg",
    image: passionfruit,
    seller: "Daniel Mbegu",
    date: "2025-10-20",
    wholesale: false,
    contact: "0766998877",
    category: "fruits",
    region: "Iringa",
    status: "Available",
  }
];